excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://erdence.github.io
title: machined rugs
# tagline:
# description: The work and progress of a work-in-progress.
description: A misplaced space
paginate: 1
